### ISSUE TITLE
local development issue

### ISSUE THREAD

**Issue by rahulkiller104** [llaske/cordova-plugin-sugarizeros#9]
@llaske   why I am getting this error while setup the local environment for android.

 Build Cordova debug version
Cannot find module '../../src/cordova/platform_metadata'
--- Sign release version
--- Copy APK to output
cp: cannot stat '/sugarizer-cordova/platforms/android/app/build/outputs/apk/debug/app-debug.apk': No such file or directory
Wed Sep  8 17:43:55 UTC 2021

I will be so thankful.

**Comment by llaske** [comment]
Hmmm strange. Is there any other before?

**Comment by rahulkiller104** [comment]
@llaske  no , i am not getting any error


![Screenshot_20210909_085602](https://user-images.githubusercontent.com/56788144/132618728-41dab928-a634-4004-b8fc-22586acf29a4.png)
![Screenshot_20210909_091018](https://user-images.githubusercontent.com/56788144/132618766-4782270c-3644-4891-afa9-e1d81cd19997.png)

**Comment by llaske** [comment]
Cannot reproduce it on my side.
Could you send me the full trace? You could use the `full` option to reduce the log size and to speed build up.
Plus, if you're using a VPN, disable it before launching the command.

**Comment by rahulkiller104** [comment]
@llaske I am not using any VPN,
i am using this command as mentioned in Readme.MD

sudo docker run --rm -it -v "`pwd`/sugarizer:/sugarizer" -v "`pwd`/cordova-plugin-sugarizeros:/cordova-plugin-sugarizeros" -v "`pwd`:/output" llaske/sugarizer-apkbuilder:latest

and  for this issue
Cannot find module '../../src/cordova/platform_metadata'
i have found in StackOverflow , i should use  these command
 npm uninstall -g cordova
 npm install -g cordova@7.1.0

**Comment by llaske** [comment]
Cordova version installed in the APK Builder image is Cordova 10.0.0 so I don't think the error you've found on StackOverflow could be related to your issue.

Could you use the command:

    sudo docker run --rm -it -v "pwd/sugarizer:/sugarizer" -v "pwd/cordova-plugin-sugarizeros:/cordova-plugin-sugarizeros" -v "pwd:/output" llaske/sugarizer-apkbuilder:latest full > build.log

Then post here the content of the `build.log` file generated by the command.

**Comment by rahulkiller104** [comment]
[build.log](https://github.com/llaske/cordova-plugin-sugarizeros/files/7148040/build.log)

@llaske  this is build.log file ,could you download it please.

**Comment by llaske** [comment]
@rahulkiller104 I think you're not using the latest version of `llaske/sugarizer-apkbuilder` image.
More precisely I think that your local version of `llaske/sugarizer-apkbuilder:latest` image is not the latest image.
You're using a version of the image with Cordova 7 inside thought I've update to Cordova 10 few month ago. See [here](https://hub.docker.com/r/llaske/sugarizer-apkbuilder/tags?page=1&ordering=last_updated).

To check it, launch the following command:

```
   $ sudo docker images | grep apkbuilder
   llaske/sugarizer-apkbuilder      cordova10           acb657b83963        6 months ago        7.96GB
   llaske/sugarizer-apkbuilder      latest              acb657b83963        6 months ago        7.96GB
   llaske/sugarizer-apkbuilder      cordova7            5f3e465037c2        9 months ago        7.48GB
   llaske/sugarizer-apkbuilder      gradle              5f3e465037c2        9 months ago        7.48GB
```
If `llaske/sugarizer-apkbuilder` identifier is `5f3e465037c2`, you're not using  the latest one.

In this case, you should remove the image using `sudo docker rmi 5f3e465037c2`.
Then relaunch the build command.

**Comment by rahulkiller104** [comment]
@llaske I have  uninstalled the previous version and installed the latest version,but i am getting same issue again.

[build.log](https://github.com/llaske/cordova-plugin-sugarizeros/files/7151225/build.log)
this is build.log file

![Screenshot_20210913_091203](https://user-images.githubusercontent.com/56788144/133020935-9a0d8ae1-ae7a-451c-800d-7f3e455308ca.png)

**Comment by llaske** [comment]
Hmmm. Are you sure? The error message `Plugin doesn't support this project's cordova-android version. cordova-android: 9.0.0, failed version requirement: <6.3.0` let me think that you're still using the old version.

Could you try forcing build build with the Cordova 10 version with this command line:

```
sudo docker run --rm -it -v "pwd/sugarizer:/sugarizer" -v "pwd/cordova-plugin-sugarizeros:/cordova-plugin-sugarizeros" -v "pwd:/output" llaske/sugarizer-apkbuilder:cordova10 full
```

**Comment by rahulkiller104** [comment]
@llaske  I unistalled everthing sugarizer ,cordova-plugin-sugarizeros,previous docker image and installed everthing from starting, but i am getting same error. Docker img is also updated.

i also tried this, but nothing is working
`sudo docker run --rm -it -v "pwd/sugarizer:/sugarizer" -v "pwd/cordova-plugin-sugarizeros:/cordova-plugin-sugarizeros" -v "pwd:/output" llaske/sugarizer-apkbuilder:cordova10 full
`
please can you check on your computer once? may be this issue is from your side.

**Comment by llaske** [comment]
@rahulkiller104 I've removed all my local docker images and relaunch the command and it works on my side.

Could you launch the following command an tell me what you obtain:

```
sudo docker run --rm -it -v "`pwd`/sugarizer:/sugarizer" -v "`pwd`/cordova-plugin-sugarizeros:/cordova-plugin-sugarizeros" -v "`pwd`:/output" --entrypoint /usr/bin/cordova llaske/sugarizer-apkbuilder:latest --version
```

(you could be asked about statistics, you could answer y or n)

**Comment by rahulkiller104** [comment]
@llaske  yes  i am getting this message , ithink all files are also present in suagr labs directory.
Thanks for opting into telemetry to help us improve cordova.
10.0.0


![Screenshot_20210916_014348](https://user-images.githubusercontent.com/56788144/133502917-8ce13903-b9f8-46e2-a438-2e704c1dfc52.png)

**Comment by llaske** [comment]
Ok. Could you try to launch the command:

```
docker run --rm -it  -v "`pwd`/sugarizer:/sugarizer"  -v "`pwd`/cordova-plugin-sugarizeros:/cordova-plugin-sugarizeros"  -v "`pwd`:/output" --entrypoint /bin/bash  llaske/sugarizer-apkbuilder:latest
```

Then on the CLI type command:

```
./make_android.sh full
```

**Comment by rahulkiller104** [comment]
@llaske  same issue again.
![Screenshot_20210917_151213](https://user-images.githubusercontent.com/56788144/133762396-65e795f2-afc6-4e53-b0d6-b959ab869212.png)

**Comment by rahulkiller104** [comment]
@llaske  I will remove everything from the desktop.
could you tell me what package I should install what should be the version from scratch?

**Comment by rahulkiller104** [comment]
@llaske thanks,  issue solved

**Comment by llaske** [comment]
Ok. Good to hear but to be honest I'm not sure to understand why 😅

**Comment by rahulkiller104** [comment]
@llaske I  removed everything again and  but this time everything works fine, i got sugarizer.apk

and a great thanks to you
